# Generated by Django 5.2.7 on 2026-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
    ]
