# Generated by Django 5.2.7 on 2026-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_expires',
            field=models.DateField(blank=True, help_text='User access will be revoked after this date.', null=True),
        ),
    ]
