# Generated by Django 5.2.7 on 2026-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
